### ISSUE TITLE
Create a browser bundle

### ISSUE THREAD

**Issue by smth** [PureCars/css-scroll-snap-polyfill#2]
I can't get this to work. With my original CSS (below) I was getting errors. In Chrome: 
```
Uncaught TypeError: Cannot read property 'y' of undefined
    at z (css-scroll-snap-polyfill.umd.js:1)
    at C (css-scroll-snap-polyfill.umd.js:1)
```
Firefox:
```
TypeError: t is undefined css-scroll-snap-polyfill.umd.js:1:16945
z css-scroll-snap-polyfill.umd.js:1:16945
C css-scroll-snap-polyfill.umd.js:1:16518
```
I then tried adding `scroll-snap-align` to the `body`. That stops the error, but nothing is happening in terms of the scrolling. Either version of the CSS works in Safari.

My HTML/CSS is equivalent to :
```html
<body>
  <main>
    <header>
    <section>
      <div></div>
      <div></div>
    </section>
  </main>
</body>
```
```CSS
body {
  scroll-snap-type: y mandatory;
}
header {
  height: 100vh;
}
section > div {
  height: 100vh;
  scroll-snap-align: start;
}
```
